name: Build and test
description: Build code, then run unit tests and autotester
env:
  BUILD_TYPE: Release

runs:
  using: composite
  steps:
    - name: Create Build Environment
      run: cmake -E make_directory build
      shell: bash

    - name: Configure CMake
      shell: bash
      working-directory: ./build
      run: |
        cmake $GITHUB_WORKSPACE/Team30/Code30/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ./build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Unit test
      shell: bash
      working-directory: ./build
      run: ./src/unit_testing/unit_testing

    - name: autotest
      shell: bash
      working-directory: ./23s1-cp-spa-team-30
      run: |
        ../build/src/autotester/autotester Team30/Tests30/source/test1-source.txt Team30/Tests30/queries/test1-parent-queries.txt Team30/Tests30/output/test1-parent-queries.xml

