name: Autotest
env:
  BUILD_TYPE: Release

runs:
  using: composite
  steps:
    - name: autotest
      shell: bash
      run: |
        ./build/src/autotester/autotester Team30/Tests30/source/test1-source.txt Team30/Tests30/queries/test1-parent-queries.txt Team30/Tests30/output/test1-parent-queries.xml


