name: Push Autotester Output to Branch

inputs:
  branch-name:
    require: true
  git-pat:
    require: true

runs:
  using: composite
  steps:
    - name: push-to-branch
      shell: bash
      env:
        GIT_PAT: ${{ inputs.git-pat }}
      # run: git branch
      run: |
        git config --global user.name 'lkwlkww'
        git config --global user.email 'lkwlkwlkww@gmail.com'

        # git fetch origin
        # git checkout origin/${{ inputs.branch-name }}

        git add ./index.html
        git commit -m 'Github actions workflow: Add html file for viewing autotester output'
        git push
        # git push origin ${{ inputs.branch-name }}
