name: Push Autotester Output to Branch

inputs:
  branch-name:
    require: true
  git-pat:
    require: true
  GITHUB_TOKEN:
    require: true

runs:
  using: composite
  steps:
    - name: push-to-branch
      shell: bash
      env:
        GIT_PAT: ${{ inputs.git-pat }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        echo "Pushing autotester output to branch ${{ inputs.branch-name }}..."
        if [ ${{ inputs.branch-name }} == 'master' ]; then
          git checkout ${{ inputs.branch-name }}
        else
          git checkout -b ${{ inputs.branch-name }}
        fi
        git config pull.rebase false
        git pull origin ${{ inputs.branch-name }}
        git add ./index.html
        git add -f Team30/Tests30/output/*
        git commit -m 'Github Actions Workflow: Add autotester output'
        git push --set-upstream --force-with-lease origin ${{ inputs.branch-name }}
