name: codecov workflow

on:
  pull_request:
    branches: [master]
  push:
    branches: [try-codecov]
  workflow_dispatch:
    branches:
      - try-codecov
      - master

jobs:
  get-code-coverage:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Set up compiler path
        run: |
          echo "PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:$PATH" >> $GITHUB_ENV
      - name: Build with Cmake
        working-directory: /Users/papattaradaapithanangsiri/23s1-cp-spa-team-30/Team30/Code30
        run: |
          pwd
          echo ${{runner.workspace}}
          mkdir -p build
          cd build
          cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ "-DCMAKE_CXX_FLAGS=-fprofile-instr-generate -fcoverage-mapping" "-DCMAKE_C_FLAGS=-fprofile-instr-generate -fcoverage-mapping" ..
          make

      - name: Build unit test
        working-directory: /Users/papattaradaapithanangsiri/23s1-cp-spa-team-30/Team30/Code30/build
        run: |
          cmake --build . --target unit_testing

      - name: Set up environment for coverage
        run: |
#          export LLVM_PROFILE_FILE="${{ runner.workspace }}/default.profraw" >> $GITHUB_ENV
          export LLVM_PROFILE_FILE="/Users/papattaradaapithanangsiri/23s1-cp-spa-team-30/Team30/Code30/default.profraw" >> $GITHUB_ENV

      - name: Run unit test
        working-directory: /Users/papattaradaapithanangsiri/23s1-cp-spa-team-30/Team30/Code30/build/src/unit_testing
        run: |
          ./unit_testing

      - name: Generate codecov report
        run: |
          llvm-profdata merge -sparse /Users/papattaradaapithanangsiri/23s1-cp-spa-team-30/Team30/Code30/default.profraw -o code_coverage.profdata
          llvm-cov show /Users/papattaradaapithanangsiri/23s1-cp-spa-team-30/Team30/Code30/build/src/unit_testing/unit_testing -instr-profile=code_coverage.profdata > coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt  # Adjusting to the correct file
          flags: unittests
          working-directory: /Users/papattaradaapithanangsiri/23s1-cp-spa-team-30/Team30/Code30/build/src/unit_testing  # If the file is relative to this path




