name: PR
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          cd Team00/Code00
          mkdir build
          cd build
          cmake ..
          make -i
      - run: ./Team00/Code00/build/src/unit_testing/unit_testing
  run_autotester:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          cd Team00/Code00
          mkdir build
          cd build
          cmake ..
          make -i
      - run: |
          cd Team00/Code00
          ./build/src/autotester/autotester tests/Sample_source.txt Sample_queries.txt out.xml

