name: PR
on:
  push:
    branches:
      - master
  pull_request:
env:
  BUILD_TYPE: Release
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team30/Code30/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config $BUILD_TYPE

      # - name: Unit test
      #   working-dircetory: ${{runner.workspace}}
      #   run: ./Team30/Code30/build/src/unit_testing/unit_testing

      - name: autotest
        working-directory: ${{runner.workspace}}
        run: pwd
      - run: ls
        # run: ./Code30/build/src/autotester/autotester Tests30/source/test1-source.txt Tests30/queries/test1-parent-queries.txt Tests30/output/test.txt
  # run_unit_tests:
    # runs-on: macos-latest
    # steps:
    #   - uses: actions/checkout@v3

    #   - name: build
    #     run: |
    #       cd Team30/Code30
    #       mkdir build
    #       cd build
    #       cmake ..
    #       # make unit_testing
    #       make unit_testing

    #   - run: ./Team30/Code30/build/src/unit_testing/unit_testing
