name: PR
on: pull_request
jobs:
  run_autotester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: |
          cd Team00/Code00
          mkdir build
          cd build
          cmake ..
      - name: make
        run: |
          cd Team00/Code00/build
          make -i

