name: PR
on: pull_request
jobs:
  run_autotester:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd Team00/Code00/
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j4

